services:
  - type: web
    name: osint-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8068204110:AAELqo2Dres3tX5pvlC5O2wopyqFwaP2AM0
      - key: AUTHORIZED_KEY
        value: secretkey123
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD 
        value: admin
        generateValue: true